### ISSUE TITLE
Support board revision 900093/BCM2708

### ISSUE THREAD

**Issue by sirdiego** [calcinai/phpi#7]
My Pi Zero does throw this Exception when executing info.php

`PHP Fatal error:  Uncaught Calcinai\PHPi\Exception\UnsupportedBoardException: Board revision [900093/BCM2708] is not (yet) supported.`

**Comment by calcinai** [comment]
This should be easy enough to add - can you please test adding `900093` to the switch/case list for PiZero in [src/Factory.php](https://github.com/calcinai/phpi/blob/5cb4b2dbaa6af23190c73f77a318f72bbf2781e5/src/PHPi/Factory.php#L65) and see if this helps?

If it does, either raise a PR or let me know so I can merge it in.

**Comment by calcinai** [comment]
I've fixed this in  a6243fc

**Comment by sirdiego** [comment]
Thank you so much! I was a litte slow on this one... Thank you for your work. We also need a bit more to use the Zero #8 .

**Comment by calcinai** [comment]
No problem.  The more people that can make use of it the better!  Sorry I mucked up you PR, but the code should now be up-to-date.

Other than these issues, has it all worked for you?
